channels:
- conda-forge
dependencies:
- python=3.10.18
- pip<=25.2
- pip:
  - mlflow==3.5.1
  - cloudpickle==3.1.1
  - numpy==2.2.5
  - packaging==25.0
  - pandas==2.3.3
  - psutil==7.0.0
  - pyarrow==20.0.0
  - pyyaml==6.0.3
  - scikit-learn==1.7.1
  - scipy==1.15.3
name: mlflow-env
